# Generated by Django 3.0.8 on 2020-07-17 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addStudent', '0004_addstudents_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('status', models.CharField(default='PENDING', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('answer', models.CharField(max_length=1000, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='addStudent.addStudents')),
            ],
        ),
    ]
