# Generated by Django 3.0.8 on 2020-07-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('mail_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=500)),
                ('phone_no', models.CharField(max_length=500)),
                ('Branch', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=500)),
            ],
        ),
    ]
